a = input('Digite algo: ')
	print('O tipo primitivo desse valor é ',type(a))
	print('Só tem espaços? ', a.isspace())
	print('E um numero? ', a.isnumeric())
	print('E alfabético? ', a.isalpha())
	print('E alfanumérico? ', a.isalnum())
	print('Está em maiúsculas? ', a.isupper())
	print('Esta em minúsculas? ', a.islower())
	print('Esta capitalizada? ', a.istitle())